version: "3.9"

services:
  dreissig-plus-eins-bot:
    build: .
    depends_on:
      - db
    env_file:
      - ./.env
    environment:
      - ORM_HOST=db
      - ORM_PORT=5432
  db:
    image: postgres
    ports:
      - "5432:${POSTGRES_PORT}"
    env_file:
      - ./.env
    volumes:
      - dreissig-plus-eins-bot-db:/var/lib/postgresql/data

volumes:
  dreissig-plus-eins-bot-db:
    name: dreissig-plus-eins-bot-db